export default {
	semi: false,
	singleQuote: false,
	trailingComma: "all",
	tabWidth: 2,
	useTabs: true,
	plugins: ["@ianvs/prettier-plugin-sort-imports"],

	importOrder: [
		"^@effect/vitest($|/.*)$",
		"^effect($|/.*)$",
		"^@effect($|/.*)$",
		"",
		"^@tanstack($|/.*)$",
		"",
		"^react($|/.*)$",
		"",
		"<BUILTIN_MODULES>",
		"",
		"<THIRD_PARTY_MODULES>",
		"",
		"^@repo/domain/.*$",
		"",
		"^@repo/.*$",
		"",
		"^@/.*$",
		"",
		"^[.]",
		"",
		".css$",
	],
}